theme: null
markdown: kramdown
plugins: []
exclude:
  - LICENSE
  - .vscode/
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - package-lock.json
  - .DS_Store
include:
  - .htaccess
